name: local save

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 * * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3

      - name: run py
        run: |
          python3 ./1.py
          echo "ok"
          
      
